version: '3'
services:
  2-publish_events_to_rabbitmq-mysql:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: adminpassword
      MYSQL_DATABASE: ecommerce
      MYSQL_USER: codely
      MYSQL_PASSWORD: c0d3ly7v
      TZ: UTC
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./databases/ecommerce.sql:/docker-entrypoint-initdb.d/init.sql

  2-publish_events_to_rabbitmq-rabbitmq:
    image: 'rabbitmq:3.12-management'
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=codely
      - RABBITMQ_DEFAULT_PASS=codely

volumes:
  db_data:
